### ISSUE TITLE
mysql connection on multiple files.

### ISSUE THREAD

**Issue by jegger06** [jegger06/edyscalculia_app#1]
Set up the mysql connection for multiple files.

**Comment by jegger06** [comment]
Check this out...

https://codereview.stackexchange.com/questions/120331/passing-node-js-sql-connection-to-multiple-routes

**Comment by jreybaylen** [comment]
Check this out dude, maybe it will helped you. [https://stackoverflow.com/export-var-to-routes-files-expressjs](https://stackoverflow.com/questions/23097689/export-var-to-routes-files-expressjs/23098092#23098092)

**Comment by jegger06** [comment]
Updated the file and now it works.
